# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b4cf2e467ded55cff3ba04450d707a50fb20b5a484ac88b44a4978e9c2aeace16eb4de3a57f2444e35f637763558f57acc4cd7afdbb9a16ba853796fd41e6f7

test:
  secret_key_base: 045fc2f93fd883244ef8d33235a83849e460d2b3759e4b32a390a9072eebc0c7570d88bf8bf9aa3d3635fca725a441416d991d39cd213ccbe11925d08e88e177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
